
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[163] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   60,   58,
        1,    1,   34,   45,   27,   33,   24,   35,   36,   26,
       41,   26,   58,   27,   19,   42,   30,   31,   30,   43,
       39,   40,   33,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   37,   33,   38,   47,   49,   50,
       47,   52,   54,   56,   57,   30,   32,   24,   24,   23,
       24,   28,   29,   20,   51,   55,   20,   19,   44,   44,
       33,   43,   43,   43,   43,   43,   43,   43,    5,   43,
       43,   43,    3,   43,   43,   43,   43,   43,   43,   46,
       48,   52,   53,   56,   56,   21,   24,   25,   24,   24,

        0,   20,    0,   20,   43,   43,   43,   43,   43,   43,
       43,   43,    4,    6,   43,   43,   43,   43,   43,   56,
       24,   24,   22,   20,   43,   17,   14,   43,   43,   43,
       11,   43,   43,   43,   43,    8,   43,   13,   43,   43,
       43,    7,   43,   43,   43,   12,   43,   43,   15,   43,
       16,    9,   43,   10,   43,   18,   43,   43,   43,   43,
        2,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   19,   19,   19,   23,   19,    1,   24,   25,
       26,   27,    1,    1,   28,   28,   28,   28,   29,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   41,   44,   45,   41,   46,
       47,   48,   41,   49,   50,   51,   52,   53,   54,   41,
       41,   41,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    3,    1,
        1,    4,    1,    1,    1,    5,    1,    6,    7,    7,
        7,    7,    7,    1,    1,    1,    1,    7,    7,    1,
        1,    1,    1,    7,    6,    6,    7,    7,    7,    6,
        7,    7,    7,    7,    7,    6,    7,    7,    6,    7,
        6,    7,    6,    7,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[174] =
    {   0,
        0,    0,   55,   56,  395,  394,  402,  401,  403,  408,
      408,  408,  376,  408,  408,  393,   58,  408,  408,  387,
      408,  384,   50,   62,   74,  408,   40,  372,   49,   62,
      408,  408,  408,   86,   75,   52,   53,   67,   79,  348,
       39,   66,   74,   69,  408,  340,  408,  408,  408,  408,
      392,    0,  377,  362,  408,  408,  408,  117,  118,  408,
      144,  408,  408,  118,  408,  408,  147,  182,  376,  209,
      408,    0,  342,   93,   80,   28,   85,  103,  102,   95,
      109,  341,  340,  110,  128,  123,  138,  139,  140,  408,
      408,    0,  408,  357,  160,  408,  227,  408,  124,  176,

      195,  220,  232,  179,  111,  157,  338,  186,  129,  163,
      170,  185,  337,  336,  177,  195,  197,  219,  211,    0,
      252,  255,  408,  269,  221,  335,  334,  223,  222,  230,
      333,  233,  244,  332,  232,  331,  255,  330,  250,  252,
      259,  329,  257,  254,  260,  328,  258,  262,  320,  341,
      308,  303,  266,  302,  316,  265,  292,  264,  150,   78,
        0,  408,  315,  322,  329,  336,  339,  341,  347,  353,
      360,  367,  369
    } ;

static yyconst flex_int16_t yy_def[174] =
    {   0,
      162,    1,  163,  163,  164,  164,  165,  165,  162,  162,
      162,  162,  162,  162,  162,  162,  166,  162,  162,  162,
      162,  162,  162,  162,  167,  162,  162,  162,  162,  168,
      162,  162,  162,  168,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,  162,  162,  162,  162,  162,  162,
      169,  170,  162,  171,  162,  162,  162,  172,  172,  162,
      172,  162,  162,  162,  162,  162,  162,  167,  167,  167,
      162,  173,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,  162,
      162,  170,  162,  171,  171,  162,  172,  162,  172,  172,

      162,  162,  162,   70,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,  171,
      172,  172,  162,  162,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,  173,
       34,   34,   34,   34,  173,   34,  173,  173,  173,  173,
      173,    0,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162
    } ;

static yyconst flex_uint16_t yy_nxt[466] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   15,   20,   21,   22,   23,   24,   25,   25,   25,
       25,   25,   25,   26,   27,   28,   29,   30,   30,   31,
       10,   32,   33,   30,   30,   34,   35,   36,   37,   38,
       30,   30,   39,   30,   30,   30,   30,   40,   41,   42,
       30,   30,   43,   44,   45,   46,   47,   49,   49,   59,
       50,   50,  107,   59,   71,   56,   60,   64,   64,   64,
       64,   64,   64,   65,   56,   71,   73,   86,   66,   72,
       72,   72,   72,   72,   72,   51,   51,   73,   61,   67,
       78,   68,   68,   68,   68,   68,   68,   80,   79,  161,

       73,   73,   70,   72,   72,   72,   72,   72,   72,   75,
       89,   81,   70,   82,   73,   73,   76,   73,   83,   87,
       88,   77,   73,   73,   84,   96,   98,   73,   73,  106,
      108,  105,  123,   73,   74,   64,   64,   64,   64,   64,
       64,   73,  109,   73,  111,  125,  101,   97,   97,   99,
       73,   73,  100,  110,   97,  112,  101,   73,   73,   73,
      114,   99,  120,  129,  102,  102,  102,  102,  102,  102,
      115,   73,  160,  116,   97,  101,   73,   73,   99,   99,
      117,  118,  119,   99,  123,  101,   73,   73,   73,   99,
       95,  162,   99,  162,   99,  126,   99,   67,  130,   68,

       68,   68,   68,   68,   68,   73,   97,  103,  131,  103,
       70,   73,  124,  124,  124,  124,  124,  124,   73,  132,
       70,  103,  133,  103,  162,   73,  104,  104,  104,  104,
      104,  104,  121,   73,   73,  122,  128,  102,  102,  102,
      102,  102,  102,   73,  121,   73,  134,  135,  101,  124,
      124,  124,  124,  124,  124,  137,  136,   97,  101,   73,
       98,  121,  121,   98,  138,  139,  121,   73,  145,   73,
       73,   73,  121,  140,  141,  121,  150,  121,   73,  121,
       73,   73,   97,  142,  159,   97,  124,  124,  124,  124,
      124,  124,   73,  146,  143,  147,  148,  149,   73,  151,

       73,  152,   73,   73,  156,   73,   73,   73,   73,  153,
       73,  158,  154,   73,   73,   48,   48,   48,   48,   48,
       48,   48,   52,   52,   52,   52,   52,   52,   52,   54,
       54,   54,   54,   54,   54,   54,   58,  157,   58,   58,
       58,   58,   58,   69,   69,   69,   73,   73,   91,   91,
       73,   73,   91,   92,   92,   92,   73,   92,   92,   92,
       94,  155,   94,   94,   94,   94,   94,   59,   73,   59,
       59,   59,   59,   59,   72,   72,   73,   73,   73,   73,
      144,   73,   73,   73,   73,   73,  127,   95,   73,  113,
       73,  162,   95,   93,   90,   57,   85,   56,   63,   62,

       57,   56,  162,   55,   55,   53,   53,    9,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162
    } ;

static yyconst flex_int16_t yy_chk[466] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,   17,
        3,    4,   76,   17,   27,   27,   17,   23,   23,   23,
       23,   23,   23,   24,   29,   29,   76,   41,   24,   30,
       30,   30,   30,   30,   30,    3,    4,   41,   17,   25,
       36,   25,   25,   25,   25,   25,   25,   37,   36,  160,

       36,   37,   25,   34,   34,   34,   34,   34,   34,   35,
       44,   38,   25,   38,   42,   38,   35,   44,   39,   42,
       43,   35,   43,   35,   39,   58,   59,   39,   75,   75,
       77,   74,   99,   77,   34,   64,   64,   64,   64,   64,
       64,   74,   78,   80,   80,  105,   64,   58,   59,   61,
       79,   78,   61,   79,   99,   81,   64,   81,   84,  105,
       84,   61,   95,  109,   67,   67,   67,   67,   67,   67,
       85,   86,  159,   86,   61,   67,   85,  109,   61,   61,
       87,   88,   89,   61,  100,   67,   87,   88,   89,   61,
       95,  104,   61,  104,   61,  106,   61,   68,  110,   68,

       68,   68,   68,   68,   68,  106,  100,  101,  111,  101,
       68,  110,  101,  101,  101,  101,  101,  101,  111,  112,
       68,   70,  115,   70,   70,  115,   70,   70,   70,   70,
       70,   70,   97,  112,  108,   97,  108,  102,  102,  102,
      102,  102,  102,  116,   97,  117,  116,  117,  102,  103,
      103,  103,  103,  103,  103,  119,  118,   97,  102,  119,
      121,   97,   97,  122,  125,  128,   97,  118,  135,  125,
      129,  128,   97,  129,  130,   97,  143,   97,  130,   97,
      135,  132,  121,  132,  158,  122,  124,  124,  124,  124,
      124,  124,  133,  137,  133,  139,  140,  141,  139,  144,

      140,  145,  144,  137,  153,  143,  147,  141,  145,  147,
      148,  157,  148,  156,  153,  163,  163,  163,  163,  163,
      163,  163,  164,  164,  164,  164,  164,  164,  164,  165,
      165,  165,  165,  165,  165,  165,  166,  155,  166,  166,
      166,  166,  166,  167,  167,  167,  168,  168,  169,  169,
      154,  152,  169,  170,  170,  170,  151,  170,  170,  170,
      171,  150,  171,  171,  171,  171,  171,  172,  149,  172,
      172,  172,  172,  172,  173,  173,  146,  142,  138,  136,
      134,  131,  127,  126,  114,  113,  107,   94,   83,   82,
       73,   69,   54,   53,   51,   46,   40,   28,   22,   20,

       16,   13,    9,    8,    7,    6,    5,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[60] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1605109.l"
/**
* Flex offline
* Lexical Analyzer
* 
* $ make
* $ ./a.out <input_file>
* 
* Rafid Bin Mostofa
* June 01 2019 0129
**/
#line 15 "1605109.l"
	#include <bits/stdc++.h>
	#include "SymbolTable.h"
	#include "1605109.tab.h"
	using namespace std;
	
	/* total errors */
	int tot_err = 0;
	
	/* log and token file */
	// ofstream lex_tokens("lexer_tokens.txt");
	// ofstream lex_log("lexer_log.txt");
	extern ofstream f_err;
	
	/* Current string, yytext */
	string cur_str = "", cur_yytext = "";
	int start_line = yylineno;

	/* Gets the backslash character */
	char get_backslash_const(string ts) {
		if(ts.size() < 2 or ts[0] != '\\') return 0;
		
		char ch = ts[1];
		if(ch == 'n') return '\n';
		if(ch == 't') return '\t';
		if(ch == '\\') return '\\';
		if(ch == '\'') return '\'';
		if(ch == '\"') return '\"';
		if(ch == 'a') return '\a';
		if(ch == 'f') return '\f';
		if(ch == 'r') return '\r';
		if(ch == 'b') return '\b';
		if(ch == 'v') return '\v';
		if(ch == '0') return '\0';
	}
	
	/* Converts a string to upper case */
	string str_uppper(string ts) {
		for(char &c : ts) c = toupper(c);
		return ts;
	}
	
	/* Does the printing */
	void prnt(string c_token, string log_yytext=yytext, string c_yytext=yytext, bool c_keyword=false, bool multi_line = false) {
		// lex_tokens << "<" << c_token;
		// if(!c_keyword) lex_tokens << ", " << c_yytext;
		// lex_tokens << "> ";
		// lex_log << "Line No. " << (multi_line ? start_line : yylineno) << ": Token <" << c_token;
		// lex_log << "> Lexeme " << log_yytext << " found\n\n";
	}
	
	/* Prints error */
	void prnt_err(string err_msg, string c_yytext=yytext, bool multi_line=false) {
		f_err << "Error at line " << (multi_line ? start_line : yylineno) << ": " << err_msg << " " << c_yytext << "\n\n"; 
		++tot_err;
	}
	
	/* take care of punctuations */
	void prnt_punct(string c_token) {
		prnt(c_token);
	}
/* Little thingies */
/* TOKENS */



#line 729 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define COMMENT 2
#define SL_COMMENT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 97 "1605109.l"


 /* ignore whitespaces */
#line 954 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 163 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 408 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 100 "1605109.l"
{ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 102 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "PRINTLN"); return PRINTLN; }
	YY_BREAK
/* START: KEYWORDS */
case 3:
YY_RULE_SETUP
#line 106 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "IF"); return IF;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 107 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "FOR"); return FOR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 108 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "DO"); return DO; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 109 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "INT"); return INT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 110 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "FLOAT"); return FLOAT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 111 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "VOID"); return VOID; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 112 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "SWITCH"); return SWITCH; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 113 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "DEFAULT"); return DEFAULT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 114 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "ELSE"); return ELSE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 115 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "WHILE"); return WHILE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 116 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "BREAK"); return BREAK; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 117 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "CHAR"); return CHAR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 118 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "DOUBLE"); return DOUBLE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "RETURN"); return RETURN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 120 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "CASE"); return CASE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 121 "1605109.l"
{ yylval.info = new SymbolInfo(yytext, "CONTINUE"); return CONTINUE; }
	YY_BREAK
/* END: KEYWORDS */
/* START: CONSTANTS; as per offline definitions */
case 19:
YY_RULE_SETUP
#line 127 "1605109.l"
{
		string c_token = "CONST_INT";
		prnt(c_token);
		yylval.info = new SymbolInfo(yytext, c_token);
		return CONST_INT;
	}
	YY_BREAK
/* Floating numbers */
case 20:
YY_RULE_SETUP
#line 136 "1605109.l"
{
		string c_token = "CONST_FLOAT";
		prnt(c_token);
		yylval.info = new SymbolInfo(yytext, c_token);
		return CONST_FLOAT;
	}
	YY_BREAK
/* Character thingies */
case 21:
YY_RULE_SETUP
#line 145 "1605109.l"
{
		string c_token = "CONST_CHAR";
		string c_yytext = yytext;
		c_yytext = c_yytext.substr(1, 1);
		
		prnt(c_token, yytext, c_yytext);
		yylval.info = new SymbolInfo(c_yytext, c_token);
		return CONST_CHAR;
	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 154 "1605109.l"
{
		string c_token = "CONST_CHAR";
		string c_yytext = yytext;
		char ch = get_backslash_const(c_yytext.substr(1, c_yytext.size()-2));
		c_yytext = "";
		c_yytext += ch;
		
		prnt(c_token, yytext, c_yytext);
		yylval.info = new SymbolInfo(c_yytext, c_token);
		return CONST_CHAR;
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 165 "1605109.l"
{
		prnt_err("Empty character constant error");
	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 168 "1605109.l"
{
		prnt_err("Unterminated character");
	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 171 "1605109.l"
{
		prnt_err("Multi character constant error");
	}
	YY_BREAK
/* END: CONSTANTS */
/* START: Operator & Punctuations */
case 26:
YY_RULE_SETUP
#line 179 "1605109.l"
{
		prnt_punct("ADDOP");
		yylval.info = new SymbolInfo(yytext, "ADDOP");
		return ADDOP;
	}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 184 "1605109.l"
{
		prnt_punct("MULOP");
		yylval.info = new SymbolInfo(yytext, "MULOP");
		return MULOP;
	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 189 "1605109.l"
{
		prnt_punct("INCOP");
		yylval.info = new SymbolInfo(yytext, "INCOP");
		return INCOP;
	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 194 "1605109.l"
{
		prnt_punct("DECOP");
		yylval.info = new SymbolInfo(yytext, "DECOP");
		return DECOP;
	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 199 "1605109.l"
{
		prnt_punct("RELOP");
		yylval.info = new SymbolInfo(yytext, "RELOP");
		return RELOP;
	}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 204 "1605109.l"
{
		prnt_punct("ASSIGNOP");
		yylval.info = new SymbolInfo(yytext, "ASSIGNOP");
		return ASSIGNOP;
	}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 209 "1605109.l"
{
		prnt_punct("LOGICOP");
		yylval.info = new SymbolInfo(yytext, "LOGICOP");
		return LOGICOP;
	}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 214 "1605109.l"
{
		prnt_punct("BITOP");
		yylval.info = new SymbolInfo(yytext, "BITOP");
		return BITOP;
	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 219 "1605109.l"
{ prnt_punct("NOT"); yylval.info = new SymbolInfo(yytext, "NOT"); return NOT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 220 "1605109.l"
{ prnt_punct("LPAREN"); yylval.info = new SymbolInfo(yytext, "LPAREN"); return LPAREN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 221 "1605109.l"
{ prnt_punct("RPAREN"); yylval.info = new SymbolInfo(yytext, "RPAREN"); return RPAREN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 222 "1605109.l"
{ prnt_punct("LCURL"); yylval.info = new SymbolInfo(yytext, "LCURL"); return LCURL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 223 "1605109.l"
{ prnt_punct("RCURL"); yylval.info = new SymbolInfo(yytext, "RCURL"); return RCURL; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 224 "1605109.l"
{ prnt_punct("LTHIRD"); yylval.info = new SymbolInfo(yytext, "LTHIRD"); return LTHIRD; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 225 "1605109.l"
{ prnt_punct("RTHIRD"); yylval.info = new SymbolInfo(yytext, "RTHIRD"); return RTHIRD; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 226 "1605109.l"
{ prnt_punct("COMMA"); yylval.info = new SymbolInfo(yytext, "COMMA"); return COMMA; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 227 "1605109.l"
{ prnt_punct("SEMICOLON"); yylval.info = new SymbolInfo(yytext, "SEMICOLON"); return SEMICOLON; }
	YY_BREAK
/* END: Operator and Punctuations */
/* START: Idenitifiers */
case 43:
YY_RULE_SETUP
#line 233 "1605109.l"
{
		string c_token = "ID";
		prnt(c_token);
		yylval.info = new SymbolInfo(yytext, "ID");
		return ID;
	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 239 "1605109.l"
{
		prnt_err("Invalid prefix on ID or invalid suffix on Number");
	}
	YY_BREAK
/* END: Idenitifiers */
/* START: STRING definitions */
case 45:
YY_RULE_SETUP
#line 247 "1605109.l"
{
		BEGIN(STRING);
		cur_str = "";
		cur_yytext = yytext;
		start_line = yylineno;
	}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 254 "1605109.l"
{
		prnt_err("Unterminated string", cur_yytext, true);
		BEGIN(INITIAL);
		cur_str = "";
		cur_yytext = "";
	}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 261 "1605109.l"
{
		cur_yytext += yytext;
	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 265 "1605109.l"
{
		cur_str += yytext;
		cur_yytext += yytext;
	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 270 "1605109.l"
{
		cur_str += get_backslash_const(yytext);
		cur_yytext += yytext;
	}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 275 "1605109.l"
{
		prnt_err("Unterminated string", cur_yytext, true);
		BEGIN(INITIAL);
		cur_str = "";
		cur_yytext = "";
	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 282 "1605109.l"
{
		cur_yytext += yytext;
		prnt("STRING", cur_yytext, cur_str, false, true);
		BEGIN(INITIAL);
		cur_str = "";
		cur_yytext = "";
	}
	YY_BREAK
/* END: STRING definitions */
/* START: C-COMMENT definitions */
case 51:
YY_RULE_SETUP
#line 294 "1605109.l"
{
		BEGIN(COMMENT);
		cur_yytext = yytext;
		start_line = yylineno;
	}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 300 "1605109.l"
{
		prnt_err("Unterminated comment", cur_yytext, true);
		BEGIN(INITIAL);
		cur_yytext = "";
	}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 306 "1605109.l"
{
		cur_yytext += yytext;
	}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 310 "1605109.l"
{
		cur_yytext += yytext;
		// lex_log << "Line No. " << start_line << ": Token <" << "COMMENT";
		// lex_log << "> Lexeme " << cur_yytext << " found\n\n";

		BEGIN(INITIAL);
		cur_yytext = "";
	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 319 "1605109.l"
{
		cur_yytext += yytext;
	}
	YY_BREAK
/* END: C-COMMENT definitions */
/* START: Single Line COMMENT definitions */
case 55:
YY_RULE_SETUP
#line 327 "1605109.l"
{
		BEGIN(SL_COMMENT);
		cur_yytext = yytext;
		start_line = yylineno;
	}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 333 "1605109.l"
{
		cur_yytext += yytext;
	}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 337 "1605109.l"
{
		// lex_log << "Line No. " << start_line << ": Token <" << "COMMENT";
		// lex_log << "> Lexeme " << cur_yytext << " found\n\n";
		
		BEGIN(INITIAL);
		cur_yytext = "";
	}
	YY_BREAK
case YY_STATE_EOF(SL_COMMENT):
#line 345 "1605109.l"
{
		// lex_log << "Line No. " << start_line << ": Token <" << "COMMENT";
		// lex_log << "> Lexeme " << cur_yytext << " found\n\n";
		
		BEGIN(INITIAL);
		cur_yytext = "";
	}
	YY_BREAK
/* END: Single Line COMMENT definitions */
case 58:
YY_RULE_SETUP
#line 355 "1605109.l"
{
		prnt_err("Unrecognized character");
	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 359 "1605109.l"
ECHO;
	YY_BREAK
#line 1491 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 163 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 163 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 162);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 359 "1605109.l"



// int main(int argc, char **argv) {
// 	if(argc > 1) {
// 		if(!(yyin = fopen(argv[1], "r"))) {
// 			cout << "Error! Can't open file \"argv[1]\"\n";
// 			return 1;
// 		}
// 	}

// 	cur_str = "";
// 	yylineno = 1;
// 	yylex();
	
// 	lex_tokens << "\n";
// 	lex_log << "Total Lines: " << yylineno-1 << "\n";
// 	lex_log << "Total Errors: " << tot_err << "\n";
	
// 	lex_tokens.close();
// 	lex_log.close();

// 	return 0;
// }

